[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
utility_staking = "6GQJNM2NZKYbvENEsAxkUS7RwzMVt7d9GJGW8fWLNayL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/AnZfwL19YCoSf5VoZ0VXzbOG0T7vc3-V"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
