[package]
name = "utility_staking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.18.4"

[lib]
name = "utility_staking"
crate-type = ["cdylib", "lib"]
